# Generated by Django 4.0.2 on 2022-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comentarioevaluacion_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioevaluacion',
            name='evaluacion',
            field=models.FloatField(),
        ),
    ]
