# Generated by Django 4.0.2 on 2022-03-30 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comentarioevaluacion_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioevaluacion',
            name='evaluacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
