# Generated by Django 4.0.2 on 2022-03-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_usuariotaller_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('propietario_taller', models.BooleanField(default=True)),
                ('nombre_taller', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('password', models.CharField(max_length=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.DeleteModel(
            name='UsuarioTaller',
        ),
    ]
