# Generated by Django 4.0.1 on 2022-03-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0004_usuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
