# Generated by Django 4.0.1 on 2022-04-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0005_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
